/**
 * HTTP & API Constants
 */

export const ERROR_CODES = {
    // Authentication Errors
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    SESSION_EXPIRED: 'SESSION_EXPIRED',

    // 2FA/MFA Errors
    TWO_FA_REQUIRED: 'TWO_FA_REQUIRED',
    INVALID_2FA_CODE: 'INVALID_2FA_CODE',
    TOTP_REQUIRED: 'TOTP_REQUIRED',
    INVALID_TOTP_CODE: 'INVALID_TOTP_CODE',
    BACKUP_CODE_USED: 'BACKUP_CODE_USED',

    // Password Errors
    PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
    PASSWORD_REUSE_NOT_ALLOWED: 'PASSWORD_REUSE_NOT_ALLOWED',
    PASSWORD_EXPIRED: 'PASSWORD_EXPIRED',
    INVALID_PASSWORD_RESET_TOKEN: 'INVALID_PASSWORD_RESET_TOKEN',

    // Permission Errors
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
    PERMISSION_DENIED: 'PERMISSION_DENIED',

    // Validation Errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
    INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
    INVALID_PHONE_FORMAT: 'INVALID_PHONE_FORMAT',
    RECAPTCHA_VERIFICATION_FAILED: 'RECAPTCHA_VERIFICATION_FAILED',

    // Rate Limiting
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',

    // System Errors
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    DATABASE_ERROR: 'DATABASE_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',

    // Session Errors
    SESSION_INACTIVE: 'SESSION_INACTIVE',
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    SESSION_NOT_ACTIVE: 'SESSION_NOT_ACTIVE',
    SESSION_NOT_VALID: 'SESSION_NOT_VALID',
    SESSION_NOT_VALIDATED: 'SESSION_NOT_VALIDATED',
    SESSION_NOT_VERIFIED: 'SESSION_NOT_VERIFIED',

    // Resource Errors
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION'
} as const;

export const RATE_LIMITS = {
    /** General API rate limit */
    GENERAL: {
        windowMs: 60_000,
        max: 120
    },

    /** Login rate limit */
    LOGIN: {
        windowMs: 900_000, // 15 minutes
        max: 20
    },

    /** OTP rate limit */
    OTP: {
        windowMs: 3_600_000, // 1 hour
        max: 5
    },

    /** Password reset rate limit */
    PASSWORD_RESET: {
        windowMs: 300_000, // 5 minutes
        max: 3
    }
} as const;

export const PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100
} as const;
